[project]
name = "healthbot-accen"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=1.2.0",
    "boto3>=1.43.83",
    "cohere>=7.1.0",
    "google-generativeai>=0.8.6",
    "huggingface-hub>=1.29.0",
    "langchain>=1.3.18",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.0",
    "langfuse>=4.15.1",
    "langgraph>=1.2.11",
    "openai>=3.5.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "tavily-python>=0.8.0",
]
